### ISSUE TITLE
showAlternatives not showing

### ISSUE THREAD

**Issue by moran0013** [mapzen/lrm-mapzen#35]
when using the lrm control, like so:

```javascript
LRM.control({
    waypoints: points,
    geocoder: gCoder,
    routeWhileDragging: routeDrag,
    router: L.Routing.valhalla(apiKey, "auto", { "serviceUrl": serviceUrl }),
    showAlternatives: true,
    formatter: new LRMValhalla.Formatter()
}).addTo(map);
```
no alternative routes are shown. Is this functionality currently supported? none of the examples seemed to show it. we have fed in control points that show an alternative route using an alternate routing service. 

thoughts?

**Comment by dgearhart** [comment]
sorry, alternates are currently not supported

**Comment by moran0013** [comment]
ah. thanks. solves that problem.
