### ISSUE TITLE
getting ready for leaflet 1.0

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/lrm-mapzen#46]
Leaflet combined `ILayer` and `Layer` in 1.0 , and it makes lrm broken. http://leafletjs.com/reference-1.0.0.html#control-layers

**Comment by frankbroniewski** [comment]
Is this
`TypeError: t is undefined leaflet.js:6:34`
which I receive in Firebug? Or do I need to look further for other things I might have broken?

**Comment by hanbyul-here** [comment]
@frankbroniewski Issues seemed to be solved with Leaflet Routing Machine's upgrade for Leaflet 1.0. I updated [example on master](https://github.com/mapzen/lrm-mapzen/blob/master/examples/index.html)
