### ISSUE TITLE
Error in Routing Calculations

### ISSUE THREAD

**Issue by FrancescoCellepathy** [mapzen/lrm-mapzen#54]
Hello,

I hope it is the right place to report a routing engine calculation bug. 

Here is the MapZen calculation on OSM: 
http://www.openstreetmap.org/directions?engine=mapzen_car&route=32.23573%2C34.91795%3B32.23326%2C34.91789#map=17/32.23435/34.91886

Here is the GoogleMap Calculation: 
https://www.google.pl/maps/dir/32.2348225,34.9179715/32.2322632,34.9177569/@32.2335455,34.9160102,17z/data=!3m1!4b1!4m2!4m1!3e0?hl=it

**Comment by dnesbitt61** [comment]
There is a gate marked in OSM. We allow gates but give a small time penalty which in this case forces the route to take the detour.

**Comment by FrancescoCellepathy** [comment]
Thank you for your answer. 
Now i want to reduce the gate_cost. Is the URI correct?

http://valhalla.mapzen.com/route?json={"locations":[{"lat":32.237911,"lon":34.917896,"type":"break"},{"lat":32.23408053051584,"lon":34.91953439344584,"type":"through"},{"lat":32.230015,"lon":34.922836,"type":"break"}],"costing":"auto","costing_options":{"auto":{"gate_cost":0}}}&api_key=valhalla-xxxxxxxx

It doesn't not change the cost from default (30) to 0. It always make a 'circle'.

**Comment by dnesbitt61** [comment]
There is a gate_cost (affect the cost and estimated time) plus a gate_penalty which adds a penalty to further prevent paths with gates. This is to prevent routes from going through gated areas as shortcuts. Try setting: "costing_options":{"auto":{"gate_cost":0,"gate_penalty":0}}

**Comment by FrancescoCellepathy** [comment]
It worked. Thank you very much
