### ISSUE TITLE
Tune by Turn & Search for the destination

### ISSUE THREAD

**Issue by olien** [mapzen/lrm-mapzen#56]
Hello, how can I combine the search with the routing?
I'd like to do something like this: goo.gl/O6TC5D

best regards

Oliver

**Comment by kevinkreiser** [comment]
We dont yet have a fully fledged demo showing both working in tandem to geocode the search and then use that directly to create the route. However both Pelias and Valhalla have leaflet integration as you've probably seen. So you could use those to create something like this.

We have a demo here: https://github.com/valhalla/demos/tree/gh-pages/routing that uses both the leaflet plugins to search for a location and to do point and click routing. Its not quite there to what you need but it has some of the pieces.

Viel Spaß dabei!

**Comment by hanbyul-here** [comment]
Hi @olien. On  gh-pages branch, you can see the example of Mapzen geocoder integrated into lrm. It uses [Leaflet Control Geocoder.](https://github.com/perliedman/leaflet-control-geocoder)
You can see working version [here](http://mapzen.github.io/lrm-mapzen/#point0lat=37.752&point0lng=-122.418&point1lat=37.779&point1lng=-122.391&mode=auto)

**Comment by olien** [comment]
Thank you both!
