### ISSUE TITLE
L.Routing.mapzenFormatter and options

### ISSUE THREAD

**Issue by dphiffer** [mapzen/lrm-mapzen#58]
I've been playing around with this a little bit and discovered a minor bug with how `L.Routing.mapzenFormatter` (lowercase) invokes L.Routing.MapzenFormatter (uppercase). It should pass an `options` object.

See: https://github.com/mapzen/lrm-mapzen/blob/master/src/L.Routing.MapzenFormatter.js#L173-L175

**Comment by hanbyul-here** [comment]
D'oh! Thank you for the issue!
