### ISSUE TITLE
Can't set the language to spanish

### ISSUE THREAD

**Issue by rossanag** [mapzen/lrm-mapzen#62]
Hi, according to the documentation spanish language is supported now (actually I helped to the Odin project) however I couldn't figure out how to set it.
I use mapzen router with leaflet-routing-machine.
I am facing two problems after doing the routing :
- the name of the origin/destination dissapear, it shows the word "name" (image attached)
- the texts are in english.

Thanks in advance for any tips.

Best!
Here's the code:

function crearControlRouting() {

    routeControl = L.Routing.control({

         router: L.Routing.mapzen('valhalla-A4rESty', {costing:'bicycle'}),
         formatter: new L.Routing.mapzenFormatter({language:'es-Es'}),

        plan: L.Routing.plan([], {
                geocoder: L.Control.Geocoder.nominatim({
                geocodingQueryParams: { countrycodes: 'uy'}
              }),
              reverseWaypoints: true,
              city:'Montevideo',
              language: 'sp'
            }),
        lineOptions: {
            styles:
                [
                    {color: 'black', opacity: 0.15, weight: 9}, //sombra
                    {color: 'white', opacity: 0.8, weight: 6}, // Contorno
                    {color: 'red', opacity: 1, weight: 4}] // Centro
       },
       summaryTemplate:  '<h2>Trayectoria: {name}</h2><h3>Distancia: {distance}</h3>',
       language: 'sp',        
        waypointMode:  'snap',
        collapsible: true  //nuevo
    }).addTo(mapa);

}

![irab](https://cloud.githubusercontent.com/assets/1948071/18862210/ebad21f0-8460-11e6-85ac-8d3ee81e1a2b.png)

**Comment by hanbyul-here** [comment]
Hi @rossanag . `language` options should be passes as a part of `directions_options` for `L.Routing.mapzen`. Also, language tag for Spanish is `es`. Try this one for the router part.

```
  router: L.Routing.mapzen('your-api-key', {
    costing: 'auto',
    directions_options: {
    language: 'es'
    }
  })
```

**Comment by rossanag** [comment]
@hanbyul-here thank you, what absent minded I put the options in the wrong place!. I will try it later and post the result afterwards. The directions options in the documentations confused me (my bad though):
[](https://mapzen.com/documentation/mobility/turn-by-turn/api-reference/)

_"Currently supported language tags with alias in parentheses: cs-CZ (cs), de-DE (de), en-US (en), en-US-x-pirate (pirate), es-ES (es), fr-FR (fr), it-IT (it)."_

**Comment by hanbyul-here** [comment]
@rossanag we will make docs more clear about it. Thanks for letting us know what to improve :) Let us know how it goes.

**Comment by kkowalsky** [comment]
added this to PR #64

**Comment by rossanag** [comment]
Sorry for my late response. I was with working in another project.
I did the what you suggested @hanbyul-here  but the service it is unavailable (503 error), I couldn't see if it works. I will try it tomorrow again.

**Comment by hanbyul-here** [comment]
We checked our service status, and it seems that there was no service down in recent several days. I am not very sure what was going on when you tested, but  I pushed the example using Spanish on github page. 
http://mapzen.github.io/lrm-mapzen/es-example.html

[This](https://github.com/mapzen/lrm-mapzen/blob/gh-pages/js/es.js) is javascript file that is used for the example. I hope this helps!

**Comment by rossanag** [comment]
Thanks so much @hanbyul-here I will check it out later.
Best!

**Comment by rossanag** [comment]
Worked, thanks a lot
