### ISSUE TITLE
 No 'Access-Control-Allow-Origin' to valhalla.mapzen.com

### ISSUE THREAD

**Issue by rossanag** [mapzen/lrm-mapzen#63]
Hi, I began to use mapzen to do the routing, in this case without using the control
I am not able to do this because the not Allowed origin message. The weird thing is that it works when it is used with the leaflet routing machine control. This is the code and the message.

Thanks in advance

```
function rutaAB(latA, latB)  // 
{
    var waypoints = [];
    var coords = [];
    var waysp = [];


    waypoints.length = 0;
    coords.length = 0;
    waysp.length = 0;
    if ((latA != null) && (latB != null))
    {

        var latlngA = L.Routing.waypoint(latA);
        var latlngB = L.Routing.waypoint(latB);

        waypoints.push(latlngA);
        waypoints.push(latlngB);

        var routes = null;

        routes = L.Routing.mapzen({addWaypoints: false});

        routes.route(waypoints, function(err, routes) {
             if (line) {
                 mapa.removeLayer(line);
             }

             if (err) {
                 console.log(err);
             }
             else {

                 coords = routes[0].coordinates;
                 waysp = routes[0].waypoints;
                 line = L.Routing.line(routes[0],{styles:[{color: 'black', opacity: 0.15, weight: 7}, {color: 'white', opacity: 0.8, weight: 4}, {color: '#1652F4', opacity: 1, weight: 3}]}).addTo(mapa);

                 var distanciaCerc = convertirKM(routes[0].summary.totalDistance);
                 popup = L.popup({offset: L.point(0, -30)})
                        .setLatLng(latB)
                        .setContent('<p>Distancia: <b>' + distanciaCerc + '</b></p>')
                        .openOn(mapa);

             }
       });

    }
    else
    {
        alert("Se necesita el par Origen-Destino para calcular la ruta");

    }

}


```
![routing](https://cloud.githubusercontent.com/assets/1948071/18862365/04e2b7d8-8462-11e6-818f-1ad61dfcb53b.png)

```

**Comment by hanbyul-here** [comment]
Hey, I am not sure why cors error is happening, but I can see the url for httprequest is not well formatted. (which makes 403 error) There is only one location in query (more than one location should be passed to route between points), and also api key is wrapped as object. (api key should be string)  

This is well formatted one. (Replace your-api-key part to your actual api key to see it working) 
```
https://valhalla.mapzen.com/route?json={%22locations%22:[{%22lat%22:37.752,%22lon%22:-122.418,%22type%22:%22break%22},{%22lat%22:37.779,%22lon%22:-122.391,%22type%22:%22break%22}],%22costing%22:%22auto%22,%22directions_options%22:{%22language%22:%22es%22}}&api_key='your-api-key'
```

**Comment by kevinkreiser** [comment]
yes we have an issue in which when the 403 comes back, it actually comes back from a different server than those who actually compute the routes, this server who sends the 403s doesnt send cors headers. this issue is being tracked here: https://github.com/kevinkreiser/prime_server/issues/28

**Comment by hanbyul-here** [comment]
Oh that makes sense. Thanks @kevinkreiser !

**Comment by rossanag** [comment]
@hanbyul-here I tested the link after replacing my own key, the message:
_<error><type>KeyError</type><message>''valhalla-A4rESty'' is not a valid key.</message></error>_

**Comment by kevinkreiser** [comment]
@rossanag your key shouldnt include the single quote character. it should just be `api_key=valhalla-A4rESty`

**Comment by rossanag** [comment]
@kevinkreiser thanks, it works, it returns a json file. I will try the whole code later to see if the 503 error is gone.

**Comment by hanbyul-here** [comment]
@rossanag If you could solve your problem, would you close the issue?
