### ISSUE TITLE
How to get a route without using the control?

### ISSUE THREAD

**Issue by rossanag** [mapzen/lrm-mapzen#65]
Hi, I think the question is very explanatory, I will explain a little more anyway. I want to find the route between 2 points. One of the point is nearest one to the user position and the another one is the user position. It worked while I was using the leaflet-routing-machine.js default's router. 
`routes = L.Routing.osrmv1({addWaypoints: false});`

However I changed it to routes: L.Routing.mapzen('mapzen-xxxxxx', {costing: 'bicycle'}); and it doesn't work, the router tunrs to be null.

The error message: 
_Uncaught TypeError: Cannot read property 'route' of null_

Thanks in advance for any clue. Best!

This is the code so far. 

```
function rutaAB(latA, latB)  
{
    var waypoints = [];
    var coords = [];
    var waysp = [];

    waypoints.length = 0;
    coords.length = 0;
    waysp.length = 0;
    if ((latA != null) && (latB != null))
    {
        var latlngA = L.Routing.waypoint(latA);
        var latlngB = L.Routing.waypoint(latB);
        waypoints.push(latlngA);
        waypoints.push(latlngB);

        var routes = null;

        routes: L.Routing.mapzen('mapzen-3indRB', {costing: 'bicycle'});
        // routes is null when using  L.Routing.mapzen
        //routes = L.Routing.osrmv1({addWaypoints: false}); it works
             
        routes.route(waypoints, function(err, routes) {
             if (line) {
                 mapa.removeLayer(line);
             }

             if (err) {
                 console.log(err);
             }
             else {

                 coords = routes[0].coordinates;
                 waysp = routes[0].waypoints;
                 line = L.Routing.line(routes[0],{styles:[{color: 'black', opacity: 0.15, weight: 7}, {color: 'white', opacity: 0.8, weight: 4}, {color: '#1652F4', opacity: 1, weight: 3}]}).addTo(mapa);

                 var distanciaCerc = convertirKM(routes[0].summary.totalDistance);
                 popup = L.popup({offset: L.point(0, -30)})
                        .setLatLng(latB)
                        .setContent('<p>Distancia: <b>' + distanciaCerc + '</b></p>')
                        .openOn(mapa);

             }
       });

    }
    else
    {
        alert("Se necesita el par Origen-Destino para calcular la ruta");

    }

}


```

**Comment by hanbyul-here** [comment]
Hey! I was able to see returned route object with the code below. (which is similar to yours) 

```
var sampleLatLngs = [L.Routing.waypoint(L.latLng(37.752, -122.418)), L.Routing.waypoint(L.latLng(37.779, -122.391))];

var router = L.Routing.mapzen('your-api-key', {costing: 'auto'});

var sampleFunction = function(err, routes) {
  console.log(routes);
}

var route = router.route(sampleLatLngs, sampleFunction);
```

I wonder it is actually the points that our routing engine can't find the route between. 
You can't even see returned error?

**Comment by rossanag** [comment]
I posted the error message above:
`controlrouting.js:246 Uncaught TypeError: Cannot read property 'route' of null`.

The only difference is que I don't pass the lat lng, since I don't know it in 'advance', I get this information according the actual position and the nearest spot to the actual position.

**Comment by hanbyul-here** [comment]
I just noticed that you are using colon (`:`) instead of equal sign(`=`) to assign router when `L.Routing.mapzen` is used . Do you have any reason doing this?

**Comment by rossanag** [comment]
Thanks so much!, it was a typo, my bad. I works perfectly now.
