### ISSUE TITLE
Consider how to handle routing with multiple break points where some are along the way

### ISSUE THREAD

**Issue by rmglennon** [mapzen/lrm-mapzen#69]
If you try to route with more than two break points and one is in between, it will convert anything in between from a break to a through location. This behavior is as-designed, because you can modify the route interactively by dragging.

When loading points from a list, though, this gives unexpected results. This was a support request from a user (see below for original email).

Snips of a repro case @dgearhart worked out:

URL based on the information in the test file:
http://valhalla.mapzen.com/route?json={"locations":[{"lat":40.749706,"lon":-73.991562,"street":"West 32nd Street"},{"lat":40.744370,"lon":-73.990379,"street":"West 26th Street"},{"lat":40.738121,"lon":-73.990883,"street":"East 18th Street"},{"lat":40.730949,"lon":-73.991432,"street":"Wanamaker Place"}],"costing":"auto","directions_options":{"units":"miles"}}

URL sent from the test tool:
https://valhalla.mapzen.com/route?json={"locations":[{"lat":40.749706,"lon":-73.991562,"type":"break"},{"lat":40.74437,"lon":-73.990379,"type":"through"},{"lat":40.730949,"lon":-73.991432,"type":"break"}],"costing":"auto","directions_options":{"units":"miles"}}

cc @hanbyul-here @dnesbitt61 

---

Original question from a user (see support ticket 1333):

All my points are set to ‘Break’ because the route could be very complicated so I wantet to have stops along the way. 

When I’m using for example the osrm-router, my instructions are connected to my waypoints on the map which is the expected behaviour. However, when using the mapzen-routing, the itinerary seems to skip some waypoints, say ‘you have reached your destination’ when they are still meters away from the point and don’t even go to the last point. 

This seems to be a problem when every point is a break point. If I set the point to ‘through’, that problem seems to be non-existing, but there is no way for me to know in the itinary if I’ve reached a waypoint along the way.

**Comment by hanbyul-here** [comment]
Yes, lrm-mapzen is translating any points in between to `through` styles.  I decided to do in this way since I was not sure about how to deal with dynamically added routing points. We can do in a way that 'unless there is a point type that user defined, set the point as `through`' or we can make an option to make all points break, or through 🤔 
related code :  https://github.com/mapzen/lrm-mapzen/blob/master/src/L.Routing.Mapzen.js#L292

**Comment by rmglennon** [comment]
To change the default behavior to make all points be "break" points all the time, modify this line of code:

https://github.com/mapzen/lrm-mapzen/blob/master/src/L.Routing.Mapzen.js#L292

and make `type: "through"` be `type: "break"`. Then, rebuild and reference your local, patched version of lrm-mapzen.
